Trabajo Práctico Especial: Fundamentos de la Ciencia de Datos (2026)

Grupo 14

Integrantes: Juan Cruz Higuera, Jeremías Aguilar, Santiago Silva Salvatierra

Ayudante: Duilio Deangeli

Dataset: Global Food & Nutrition Database 2026 – Health Scores & Allergens


Descripción General del Trabajo

El presente Trabajo Práctico Especial tiene como propósito aplicar los conceptos de la Ciencia de Datos sobre un conjunto de datos real vinculado a la composición nutricional, niveles de procesamiento y presencia de alérgenos en alimentos comerciales. A lo largo de esta notebook se desarrollará el flujo completo de trabajo: configuración del entorno, exploración inicial, limpieza y adecuación de variables, formulación y contraste de hipótesis estadísticas y modelado predictivo probabilístico.

Sección 1: Preparación del Entorno, Carga y Primer Diagnóstico de los Datos

Objetivo de la sección

Dejar listo el entorno de trabajo con las librerías necesarias, cargar el archivo de datos desde la carpeta local del proyecto y hacer una primera revisión completa de la tabla. La idea es conocer el tamaño de la muestra, mirar cómo vienen cargadas las filas, revisar qué tipos de datos asignó Pandas para detectar campos que necesiten corrección y analizar las pistas que nos permitan deducir de dónde salieron los datos y qué tipo de alimentos estamos estudiando realmente.

Tareas que vamos a realizar en esta sección:
Cargar las herramientas iniciales: Traer las librerías básicas para manipular tablas, calcular métricas y armar gráficos (1.1).

Leer el archivo: Cargar en memoria el dataset ubicado en la carpeta data/ usando una ruta relativa para que el proyecto funcione en cualquier máquina (1.2).   

Primer vistazo a los datos: Mostrar los primeros registros con head() para comprobar que las columnas se hayan separado bien y familiarizarnos con la información (1.3).

Revisar tamaño y tipos de datos: Usar shape e info() para ver la cantidad de productos y variables, anotando qué columnas numéricas vinieron guardadas como texto o con campos vacíos (1.4).

Deducir el origen del dataset: Analizar las columnas, sellos y nombres de variables para identificar la procedencia de los datos, entender qué universo de alimentos representan y justificar el criterio de limpieza que usaremos más adelante (1.5).

Clasificar las variables: Catalogar cada columna según su naturaleza estadística (cualitativas nominales u ordinales y cuantitativas continuas) para entender qué representa cada campo y detectar variables constantes que no varían como food_type (1.6).

Auditar valores faltantes y nulos ocultos: Medir datos vacíos formales y buscar nulos camuflados bajo textos como 'UNKNOWN', descubrir la trampa de las columnas de alérgenos donde la falta de declaración se completó con False y detectar errores de carga que rompen los límites físicos de los alimentos (1.7).

Analizar datos válidos y postergar métricas numéricas: Revisar las frecuencias de las categorías, sellos y alérgenos en los productos válidos, justificando formalmente por qué el cálculo de promedios y la detección de valores atípicos (outliers) se dejan para la etapa de limpieza (1.8).

1.1 Importacion de librerias y configuracion del entorno 

Disponer en memoria las librerías fundamentales de Python (pandas, numpy, matplotlib, seaborn) para manipular estructuras de datos tabulares, calcular estadísticas y generar visualizaciones a lo largo de todo el análisis.

In [4]:
import pandas as pd 
import numpy as np

1.2 Carga de los datos

Leer el archivo de datos ubicado en la carpeta data/.

In [5]:
data_path = "data/dataset.csv"
df_food = pd.read_csv(data_path)

Leemos el archivo dataset.csv guardado en la carpeta local data/ usando la función read_csv() de Pandas. Al usar una ruta relativa nos aseguramos de que el proyecto se pueda abrir y correr en cualquier computadora sin problemas de rutas fijas.

1.3 Primer vistazo a las observaciones

Inspeccionar visualmente las primeras filas con head() para comprobar que el archivo se haya delimitado y separado correctamente en columnas, identificando a grandes rasgos el contenido de los registros.

In [6]:
df_food.head(10)

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.0,0.0,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,65,26,False,False,False,False,False,False,Branded/Packaged
3,Eau minérale naturelle,sidi ali,"en:beverages-and-beverages-preparations, en:be...",100% mineral water,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,65,26,False,False,False,False,False,False,Branded/Packaged
4,اكوافينا,AQUAFINA,"en:beverages-and-beverages-preparations, en:be...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,508,203,False,False,False,False,False,False,Branded/Packaged
5,Lait,Jaouda,"en:dairies, en:meals, en:milks-liquid-and-powder",Lait frais pasteurisé demi-écrémé à 15g/l de m...,B,3.0,D,en:milk,45.0,1.5,...,3.1,225,0.09,False,True,False,False,False,False,Branded/Packaged
6,Eau De Source,Cristaline,"en:beverages-and-beverages-preparations, en:be...",Eau de source,A,1.0,NOT-APPLICABLE,en:none,0.0,0.0,...,0.0,275,11,False,False,False,False,False,False,Branded/Packaged
7,Fromage Blanc Nature,Milky Food Professional,"en:dairies, en:fermented-foods, en:fermented-m...","Ferments lactiques, Présure, Sel.",A,3.0,B,en:milk,80.6,12.0,...,7.3,0.0,0.0,False,True,False,False,False,False,Branded/Packaged
8,uht jaouda 1L,Jaouda,"en:dairies, en:milks-liquid-and-powder, en:milks",Lait entier,B,1.0,D,en:milk,58.0,3.0,...,3.0,0.0,0.0,False,True,False,False,False,False,Branded/Packaged
9,Jben,Jaouda,"en:dairies, en:fermented-foods, en:fermented-m...","lait frais entier, crème, stabilisants, amidon...",D,4.0,D,en:milk,235.0,21.0,...,8.0,0.46,184,False,True,False,False,False,False,Branded/Packaged

Al ejcutar head(10) comprobamos que el archivo se cargó y se separó en sus 24 columnas, mostrándonos alimentos envasados de supermercado con descripciones en francés o árabe y categorías con prefijos en inglés como en:dairies. Además, este primer vistazo ya nos deja ver varias particularidades sobre la calidad de la base, aparecen tanto valores NaN como textos que camuflan datos faltantes ('NOT-APPLICABLE' o 'UNKNOWN' en los sellos), la columna food_type es una constante todos sus valores son 'Branded/Packaged'.

1.4 Dimensiones y tipos de datos de las columnas

Relevar con shape e info() la cantidad total de filas y columnas, registrando qué variables nutricionales fueron cargadas erróneamente como texto (object) y observando la presencia preliminar de valores faltantes.

In [7]:
# Dimensiones generales
print(f"Dimensiones del dataset: {df_food.shape[0]} filas y {df_food.shape[1]} columnas\n")

Dimensiones del dataset: 4997 filas y 24 columnas

Mirando las 4.997 filas y 24 columnas, lo primero que salta a la vista es que estamos ante un recorte o muestra acotada y no frente a toda la base global de Open Food Facts, que maneja millones de productos; además, este volumen de casi 5.000 observaciones tiene el tamaño justo para un análisis exploratorio porque nos da una muestra estadísticamente sólida para calcular distribuciones, frecuencias y porcentajes sin sufrir por falta de datos, pero a la vez es lo bastante liviana como para manipularla al instante en memoria RAM con Pandas sin hacer sufrir a la máquina, logrando con sus 24 columnas un balance perfecto entre variables nutricionales, sellos y alérgenos para cruzar información sin tener una tabla sobrecargada de campos innecesarios.

In [8]:
# Estructura técnica y tipos de datos
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_name        4785 non-null   str
 1   brands              4751 non-null   str
 2   categories          4913 non-null   str
 3   ingredients         4797 non-null   str
 4   nutriscore_grade    4983 non-null   str
 5   nova_group          4522 non-null   float64
 6   ecoscore_grade      4984 non-null   str
 7   allergens           3332 non-null   str
 8   energy_kcal         4682 non-null   str
 9   fat_100g            4695 non-null   str
 10  saturated_fat_100g  4617 non-null   str
 11  carbs_100g          4676 non-null   str
 12  sugars_100g         4631 non-null   str
 13  fiber_100g          3495 non-null   str
 14  proteins_100g       4690 non-null   str
 15  salt_100g           4653 non-null   str
 16  sodium_100g         4653 non-null   str
 17  contains_gluten     4997 non-null   bool
 18  contains_dairy      4997 non-null   bool
 19  contains_nuts       4997 non-null   bool
 20  contains_soy        4997 non-null   bool
 21  contains_eggs       4997 non-null   bool
 22  contains_fish       4997 non-null   bool
 23  food_type           4997 non-null   str
dtypes: bool(6), float64(1), str(17)
memory usage: 732.1 KB

In [9]:
duplicados = df_food.duplicated().sum()
print(f"Cantidad de filas exactamente duplicadas: {duplicados}")

Cantidad de filas exactamente duplicadas: 38

Al revisar la salida de info(), notamos algunos puntos clave sobre el estado de las columnas:

Inconsistencias en tipos de datos inferidos: Enteros guardados como float: Aunque la variable nova_group representa niveles enteros de procesamiento (1, 2, 3 y 4), Pandas le asignó float64. Esto ocurre técnicamente por la presencia de valores nulos (NaN), ya que en el estándar tradicional de Pandas el valor nulo se representa como un número de punto flotante, forzando a toda la columna a convertirse a decimal para poder alojarlo.

Números guardados como texto: Columnas nutricionales que deberían ser valores numéricos continuos (energy_kcal, fat_100g, saturated_fat_100g, carbs_100g, sugars_100g, fiber_100g, proteins_100g, salt_100g, sodium_100g) fueron leídas como texto (str). Esto nos avisa que el archivo original trae comas, símbolos o caracteres extraños que no dejaron a Pandas interpretarlos como números reales, por lo que vamos a tener que limpiarlos y convertirlos en la Sección 2. 

Datos incompletos: El conjunto cuenta con 4.997 filas en total. Variables como allergens (3.332 datos presentes) o fiber_100g (3.495 datos presentes) tienen más de 1.500 campos vacíos cada una, por lo que va a ser necesario definir qué criterio usar con esos nulos.

Indicadores de alérgenos completos: Las columnas booleanas de alérgenos (contains_gluten, contains_fish, etc.) tienen sus 4.997 registros completos con valores de verdadero o falso (bool), listas para usarse sin necesidad de emparchar datos faltantes.

Filas duplicadas : Existen en el dataset 38 filas que contienen exactamente los mismos valores.

1.5 Análisis del Posible Origen y Contexto de los Datos

Analizar las marcas de identidad del dataset (sellos NOVA y Nutri-Score, prefijos en:, porciones estandarizadas en 100 g) para concluir formalmente que los datos provienen de Open Food Facts y entender las particularidades de una base alimentaria colaborativa.

Como para este trabajo se nos entrega el archivo dataset.csv sin una descripción ni documentación que explique de dónde salió, tenemos que analizar los datos por nuestra cuenta para deducir su origen. Esto es clave no solo para saber la fuente, sino para entender con qué tipo de alimentos estamos trabajando realmente, hasta dónde podemos extender nuestras conclusiones y evitar suposiciones equivocadas al plantear las hipótesis. Además, entender cómo se armó el archivo nos ayuda a explicar por qué encontramos columnas con números guardados como texto, errores al escribir o campos vacíos, dándonos un criterio claro para corregir estos problemas en la etapa de limpieza y análisis posterior.

Al revisar las columnas y los valores de la tabla, encontramos varias pistas claras que delatan de dónde salieron los datos:

Sistemas de sellos combinados: El dataset incluye al mismo tiempo nutriscore_grade, nova_group y ecoscore_grade. Esta combinación de clasificaciones nutricionales y ambientales en una misma base es la marca registrada de Open Food Facts, el proyecto colaborativo abierto más grande del mundo sobre alimentos.

Prefijos de idioma en las categorías: En columnas como categories los valores empiezan con etiquetas en inglés como en: (por ejemplo, en:beverages o en:snacks). Esta forma de ordenar las categorías es el estándar que usa Open Food Facts para que personas de distintos países puedan cargar productos bajo un mismo criterio.

Valores calculados cada 100 gramos: Todas las columnas de nutrientes (energy_kcal, sugars_100g, fat_100g, etc.) están medidas sobre una base de 100 g. Esto responde a las leyes de etiquetado obligatorio de la Unión Europea y otros países, donde los fabricantes deben informar los datos por cada 100 gramos o mililitros de producto.

Separación de alérgenos: La presencia de una columna con texto libre (allergens) junto a varias columnas con valores de verdadero o falso (contains_gluten, contains_fish, etc.) muestra que hubo un procesamiento previo para facilitar el análisis, separando los alérgenos más comunes de las declaraciones que vienen en los paquetes.

Con estas evidencias podemos afirmar que el archivo proviene de Open Food Facts. Esto significa que nuestra muestra representa alimentos procesados y envasados con código de barras (los que se compran en un supermercado), y explica por qué aparecen números escritos como texto o errores de tipeo, ya que muchos datos se cargan de forma comunitaria o mediante fotos tomadas con el celular.

1.6 Caracterización y Clasificación del Conjunto de Variables

Catalogar cada una de las 24 columnas según su escala de medición (cualitativas nominales u ordinales y cuantitativas continuas), detectando a su vez variables sin variabilidad informativa como la columna constante food_type.

Para entender la estructura de la información disponible, relevamos el significado de cada columna y clasificamos las variables según su naturaleza estadística (cualitativas o cuantitativas) y su subtipo (nominales, ordinales, continuas o discretas).

Datos descriptivos e identificación del producto:
    `product_name`: Nombre comercial del alimento. Cualitativa nominal.
    `brands`: Marca del fabricante. Cualitativa nominal.
    `categories`: Categorías taxonómicas a las que pertenece el producto Cualitativa nominal.
    `ingredients`: Listado de ingredientes declarados. Cualitativa nominal.
    `food_type`: Categoría general del producto (por ejemplo, sólido o bebida). Cualitativa nominal. Es una constante ya que todos los valores son iguales para las 4997 filas del dataset.

Sellos y sistemas de clasificación:
    `nutriscore_grade`: Evaluación global de calidad nutricional (letras A a E). Cualitativa ordinal (existe un orden de calidad evidente: la A es mejor perfil que la E).
    `nova_group`: Clasificación según grado de procesamiento industrial (niveles 1 a 4). Cualitativa ordinal (el número indica niveles crecientes de procesamiento, no una cantidad medida físicamente).
    `ecoscore_grade`: Calificación del impacto ambiental del alimento (letras A a E). Cualitativa ordinal.

Composición nutricional (medida por cada 100 g o 100 ml):
    `energy_kcal`: Aporte energético medido en kilocalorías. Cuantitativa continua.
    `fat_100g`: Contenido total de grasas en gramos. Cuantitativa continua.
    `saturated_fat_100g`: Grasas saturadas en gramos. Cuantitativa continua.
    `carbs_100g`: Hidratos de carbono en gramos. Cuantitativa continua.
    `sugars_100g`: Azúcares simples en gramos. Cuantitativa continua.
    `fiber_100g`: Fibra alimentaria en gramos. Cuantitativa continua.
    `proteins_100g`: Proteínas en gramos. Cuantitativa continua.
    `salt_100g`: Sal total en gramos. Cuantitativa continua.
    `sodium_100g`: Sodio en gramos. Cuantitativa continua.

Indicadores de alérgenos:
    `allergens`: Texto libre con los alérgenos declarados en el envase. Cualitativa nominal.
    `contains_gluten`, `contains_dairy`, `contains_eggs`, `contains_nuts`, `contains_soy`, `contains_fish`: Indicadores binarios de presencia o ausencia. Cualitativas nominales (dicotómicas / booleanas).

1.7 Diagnóstico de Valores Faltantes: La Trampa de los Alérgenos, Nulos Explícitos y Datos No Informativos

Detectar ausencias reales más allá de los nulos computacionales (NaN), identificando valores como 'UNKNOWN' o 'NOT-APPLICABLE', descubriendo la "trampa de alérgenos" (donde la falta de carga se completó falsamente con False) y registrando valores que rompen límites físicos.

Para evaluar la calidad real de la información, no alcanza con medir únicamente los vacíos formales (`NaN`) que reconoce Pandas; es necesario analizar si existen valores que esconden la falta de dato y entender cómo se generaron las columnas derivadas.

La trampa de las columnas booleanas de alérgenos:

    Al cruzar los datos observamos que en las 1.665 filas donde el texto de `allergens` es nulo (`NaN`), todas las columnas de presencia de alérgenos (`contains_gluten`, `contains_dairy`, etc.) figuran como `False`.
    Esto demuestra que estas variables son el resultado de un procesamiento automático que buscó palabras clave sobre la columna de texto y, ante la falta de información, completó con `False` por defecto.

In [10]:
#Verificación del patrón de alérgenos
filas_allergens_nulas = df_food[df_food['allergens'].isnull()]

columnas_alergenos = [
    'contains_gluten',
    'contains_dairy',
    'contains_eggs',
    'contains_nuts',
    'contains_soy',
    'contains_fish'
]

# Muestra cuántos True hay en cada alérgeno cuando allergens es NaN

conteo_por_alergeno = filas_allergens_nulas[columnas_alergenos].sum()
total_trues = conteo_por_alergeno.sum()

print(f"Total de registros con 'allergens' nulo: {len(filas_allergens_nulas)}")
print(f"Cantidad de valores True en columnas de alérgenos cuando 'allergens' es NaN: {total_trues}")

Total de registros con 'allergens' nulo: 1665
Cantidad de valores True en columnas de alérgenos cuando 'allergens' es NaN: 0

Conclusión del análisis de alérgenos
Hicimos esta prueba para entender cómo se construyeron las columnas booleanas (`contains_gluten`, `contains_dairy`, etc.) y no cometer el error de usarlas a ciegas.

Si miramos la tabla por arriba, parece que estas columnas están completas y listas para usar porque no tienen ningún valor nulo. Sin embargo, quisimos comprobar qué pasaba en las 1.665 filas donde el texto de allergens vino vacío (NaN).Como en Python un True equivale a 1 y un False equivale a 0, filtramos únicamente esos 1.665 productos y aplicamos una suma sobre las 6 columnas de alérgenos (contains_gluten, contains_dairy, etc.). Si al menos un producto hubiera tenido un True, la suma de esa columna tendría que dar 1 o más. Como el resultado fue estrictamente 0 en cada una, comprobamos que las 9.990 celdas analizadas (1.665 filas, 6 columnas) fueron completadas con False.

Con esto comprobamos que quien armó la base pasó un script que buscaba palabras clave en el texto de `allergens`, y como en esos 1.665 productos no había nada escrito, le asignó `False` por defecto a todo. 

Esto es un problema metodológico importante: que un producto no tenga cargada la lista de alérgenos no significa que sea apto para celíacos o libre de alérgenos, sino que simplemente no tenemos el dato. Tomar esos `False` como alimentos seguros distorsionaría cualquier análisis posterior, porque estamos mezclando productos que verdaderamente no tienen alérgenos con productos donde el usuario de la app no cargó la información.

Metodología para la auditoría de valores faltantes

Para realizar un relevamiento exhaustivo de la calidad de los datos, no es suficiente con cuantificar los valores nulos formales (`NaN`) mediante `isnull()`. En datasets reales es habitual encontrar nulos encubiertos o camuflados, es decir, registros con valores válidos a nivel de tipo de dato pero carentes de significado analítico.

La estrategia para detectar estos valores varía según la naturaleza de cada variable:

Variables numéricas: Además de los `NaN` tradicionales, estas columnas pueden ocultar valores discernibles o códigos de omisión (como `-1`, `0` en contextos biológicamente imposibles o `-999`). Por las leyes físicas y químicas de los alimentos, magnitudes como gramos de nutrientes o kilocalorías no pueden ser negativas. Por lo tanto, la auditoría en estas variables se realiza inspeccionando sus rangos válidos (mínimos y máximos mediante `.describe()`) para descartar la presencia de valores fuera de dominio que actúen como nulos disfrazados.

Variables de texto (tipo `object`): No resulta viable aplicar un `value_counts()` indiscriminado sobre todas las columnas para inspeccionar sus categorías. En campos de texto abierto o descripciones con alta variabilidad (como nombres de productos o listas de ingredientes), la enorme cantidad de valores únicos saturaría el análisis e impediría una revisión manual. Por este motivo, para las variables categóricas el primer paso consiste en calcular su cardinalidad (cantidad de valores únicos). Aquellas columnas con un conjunto reducido de categorías (baja cardinalidad, como escalas nutricionales y sellos ambientales) se auditarán directamente con tablas de frecuencia completa (`value_counts(dropna=False)`). Esto permitirá contrastar las categorías observadas contra los dominios teóricos de cada escala y descubrir de forma empírica qué etiquetas (como `"unknown"` o `"not-applicable"`) actúan como valores faltante. Por último, para las variables de texto libre o con alta cardinalidad (tales como nombres de productos, marcas o listas de ingredientes), donde la dispersión de valores únicos descarta tanto la revisión manual mediante tablas de frecuencias como el cálculo de estadísticos descriptivos, la detección de nulos encubiertos se aborda mediante técnicas de filtrado y análisis de patrones. Este procedimiento consiste en auditar la existencia de cadenas no informativas a través de dos mecanismos: por un lado, la identificación de registros vacíos o compuestos exclusivamente por espacios en blanco que el sistema no tipifica nativamente como ausentes; por otro, la aplicación de expresiones regulares para rastrear de forma automatizada patrones y términos genéricos de omisión comúnmente introducidos por usuarios o interfaces (tales como "none", "unknown", "n/a", guiones o signos de interrogación). De esta manera, es posible cuantificar e incorporar al diagnóstico de calidad aquellos registros sintácticamente válidos pero carentes de aporte semántico sin requerir una inspección individualizada de cada entrada.

In [11]:
for col in df_food.columns:
    # Verificamos si la columna es de texto
    if df_food[col].dtype == 'str':
        cantidad_unicos = df_food[col].nunique(dropna=False)
        print("Columna:", col, "-> Valores únicos:", cantidad_unicos)

Columna: product_name -> Valores únicos: 4418
Columna: brands -> Valores únicos: 2064
Columna: categories -> Valores únicos: 431
Columna: ingredients -> Valores únicos: 4614
Columna: nutriscore_grade -> Valores únicos: 8
Columna: ecoscore_grade -> Valores únicos: 10
Columna: allergens -> Valores únicos: 311
Columna: energy_kcal -> Valores únicos: 893
Columna: fat_100g -> Valores únicos: 694
Columna: saturated_fat_100g -> Valores únicos: 526
Columna: carbs_100g -> Valores únicos: 785
Columna: sugars_100g -> Valores únicos: 682
Columna: fiber_100g -> Valores únicos: 389
Columna: proteins_100g -> Valores únicos: 515
Columna: salt_100g -> Valores únicos: 736
Columna: sodium_100g -> Valores únicos: 664
Columna: food_type -> Valores únicos: 1

In [12]:
cols_nutrientes = [
    'energy_kcal', 'fat_100g', 'saturated_fat_100g', 'carbs_100g', 
    'sugars_100g', 'fiber_100g', 'proteins_100g', 'salt_100g', 'sodium_100g'
]
# Convertimos temporalmente a número para evaluar mínimos matemáticos reales
df_food[cols_nutrientes].apply(pd.to_numeric, errors='coerce').agg(["min","max"])

,energy_kcal,fat_100g,saturated_fat_100g,carbs_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g
min,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
max,5280.0,952.0,999.0,8989.0,952.0,6.111242e+12,733.0,988.0,975.0

Al auditar los valores máximos de las variables cuantitativas nutricionales, se constata la presencia de severas inconsistencias de carga que violan los límites físicos, biológicos y estequiométricos de los alimentos. Dado que las magnitudes están estandarizadas cada 100 gramos de producto, ningún nutriente individual puede superar matemáticamente los 100 g ni la energía sobrepasar las 900 kcal correspondientes a la grasa pura, umbrales que resultan ampliamente transgredidos al observar registros anómalos de cientos de gramos en macronutrientes, más de 5.200 kcal de energía y un valor espurio de orden billonario en fibra. Metodológicamente, se concluye que estas cifras desproporcionadas no corresponden a códigos centinela utilizados para denotar valores faltantes, sino a registros corruptos y errores de carga en la recolección de datos; esta evidencia justifica empíricamente por qué resulta inviable calcular estadísticos descriptivos como medias o desvíos estándar en esta etapa, debiendo documentar el diagnóstico en este primer ejercicio para luego sanear, filtrar o imputar dichas aberraciones durante la fase de curación y limpieza.

In [13]:
# Lista de variables cualitativas y ordinales de baja cardinalidad
cols_baja_cardinalidad = ['nutriscore_grade', 'ecoscore_grade', 'nova_group']

# Inspección exhaustiva de categorías y detección de nulos encubiertos
for col in cols_baja_cardinalidad:
    print(f"Distribución de valores en: {col}")
    print(df_food[col].value_counts(dropna=False))

Distribución de valores en: nutriscore_grade
nutriscore_grade
C                 1072
E                  995
D                  899
A                  833
B                  648
UNKNOWN            401
NOT-APPLICABLE     135
NaN                 14
Name: count, dtype: int64
Distribución de valores en: ecoscore_grade
ecoscore_grade
B                 895
A                 822
UNKNOWN           777
D                 716
C                 643
E                 508
NOT-APPLICABLE    259
A-PLUS            257
F                 107
NaN                13
Name: count, dtype: int64
Distribución de valores en: nova_group
nova_group
4.0    2637
3.0    1093
1.0     584
NaN     475
2.0     208
Name: count, dtype: int64

Al realizar las tablas de frecuencias sobre las variables cualitativas y ordinales de baja cardinalidad, se evidenció con claridad la discrepancia entre los nulos explícitos y los reales. En nutriscore_grade y ecoscore_grade, las ausencias formales mediante NaN apenas alcanzan 14 y 13 registros respectivamente; no obstante, al contrastar los valores observados contra los estándares oficiales se descubrió la presencia de etiquetas de omisión del sistema como "UNKNOWN" y "NOT-APPLICABLE", las cuales acumulan 536 y 1.036 casos encubiertos en cada escala.En la variable ecoscore_grade tambien podemos mecionar que en la tabla de frecuencias aparecen 257 casos de 'A-PLUS' y 107 de 'F'. Como la escala estándar oficial va de A a E, podemos afirmar que el dataset incluye categorías atípicas o fuera de la escala tradicional. Por su parte, la variable ordinal nova_group presentó únicamente valores dentro del dominio admisible (grupos del 1 al 4) y ausencias explícitas (NaN), descartando la utilización de códigos numéricos de relleno. Este contraste empírico confirma la necesidad metodológica de la auditoría de dominio, documentando de forma fehaciente que los verdaderos faltantes en las escalas ambientales y nutricionales superan ampliamente a los reportados por métodos tradicionales como isnull().

In [14]:
# Definimos los patrones de texto que podrian representar valores nulos no explicitos. Estos son valores que, aunque no sean NaN, indican que la información no está disponible o no es aplicable.
valores_no_informativos = ["not-applicable", "unknown", "none", "n/a", "null", "none", "nan", "void", "empty","-", "?"]

resumen_nulos_completo = [] 
for col in df_food.columns:
    # Nulos tradicionales (NaN)
    nulos_nan = df_food[col].isnull().sum()
    
    # Nulos camuflados en texto (ignorando nulos previos y espacios extra)
    if (df_food[col].dtype == 'string'):
        nulos_texto = df_food[col].dropna().astype(str).str.strip().str.lower().isin(valores_no_informativos).sum()
    else:
        nulos_texto = 0
        
    total_faltantes = nulos_nan + nulos_texto
    porcentaje_faltantes = round(total_faltantes/ len(df_food)* 100, 2)

    resumen_nulos_completo.append({
        "columna" : col,
        "nulos_explicitos" : nulos_nan,
        "nulos_camuflados" : nulos_texto,
        "total_faltantes" : total_faltantes,
        "porcentaje_faltantes" : porcentaje_faltantes
    })
df_datos_faltantes = pd.DataFrame(resumen_nulos_completo).sort_values(by="porcentaje_faltantes", ascending=False)
df_datos_faltantes

,columna,nulos_explicitos,nulos_camuflados,total_faltantes,porcentaje_faltantes
7,allergens,1665,0,1665,33.32
13,fiber_100g,1502,0,1502,30.06
6,ecoscore_grade,13,1036,1049,20.99
4,nutriscore_grade,14,536,550,11.01
5,nova_group,475,0,475,9.51
10,saturated_fat_100g,380,0,380,7.60
12,sugars_100g,366,0,366,7.32
15,salt_100g,344,0,344,6.88
16,sodium_100g,344,0,344,6.88
11,carbs_100g,321,0,321,6.42
8,energy_kcal,315,0,315,6.30
14,proteins_100g,307,0,307,6.14
9,fat_100g,302,0,302,6.04
1,brands,246,1,247,4.94
0,product_name,212,0,212,4.24
3,ingredients,200,0,200,4.00
2,categories,84,0,84,1.68
17,contains_gluten,0,0,0,0.00
18,contains_dairy,0,0,0,0.00
19,contains_nuts,0,0,0,0.00
20,contains_soy,0,0,0,0.00
21,contains_eggs,0,0,0,0.00
22,contains_fish,0,0,0,0.00
23,food_type,0,0,0,0.00

Para determinar qué palabras pueden actuar como nulos camuflados sin tener que mirar todo el archivo de antemano, nos basamos en cómo funcionan los sistemas y los formularios de carga de datos en el mundo real. Cuando un software exporta información a un archivo plano como un CSV, la falta de datos suele escribirse automáticamente con palabras técnicas reservadas (como "null", "none" o "nan"). Al mismo tiempo, en cualquier aplicación o página web donde una persona o un algoritmo clasifica un producto y no tiene el dato certero, la interfaz suele ofrecer opciones predeterminadas para no dejar la celda vacía, tales como "unknown", "not-applicable", "n/a" o simplemente un guion. Por lo tanto, no se eligen estas palabras al azar, sino que se define una lista de búsqueda estándar a partir de estas convenciones habituales de carga y exportación de datos, permitiendo auditar de manera objetiva y reproducible si el dataset contiene este tipo de respuestas por defecto.

Seccion 1.8 : Comportamiento y distribucion de las variables y outliers

Después de identificar y contar los valores que faltan, analizamos qué nos muestran los datos que sí son válidos en el dataset. En las variables de texto y categorías con pocas opciones, los porcentajes nos dejan ver claramente cómo está compuesta la muestra: más del 58% de los productos corresponden al Grupo 4 de NOVA (alimentos ultraprocesados), lo que demuestra que el dataset está muy sesgado hacia productos envasados e industriales; en Nutri-Score la mayoría se concentra en las notas C (24,2%) y E (22,5%), reflejando una calidad nutricional baja; en Eco-Score aparecen etiquetas raras o viejas como A-PLUS y F; y en los alérgenos lo que más abunda es gluten (32%) y lácteos (30%). Por el lado de los nutrientes cuantitativos (grasas, azúcares, etc.), no calculamos promedios, porcentajes ni gráficos porque todavía figuran como texto (object) en Pandas y además tienen errores de carga, como valores que superan por mucho los 100 gramos por porción. Intentar medir su distribución ahora nos daría números sin ningún sentido real, así que dejamos su conversión a números y su análisis para la Sección 2, una vez que limpiemos esos registros erróneos.
Respecto a los valores atípicos (outliers), su análisis estadístico formal también se deja para la Sección 2. Con los datos en crudo solo pudimos notar a simple vista errores groseros que rompen los límites de la física, como cantidades mayores a 100 gramos o cifras billonarias. Pero para usar técnicas reales de detección de atípicos (como boxplots), primero es obligatorio convertir las columnas de texto a números y limpiar esas cargas corruptas, ya que de lo contrario cualquier cuenta o gráfico quedaría completamente deformado por esos valores gigantescos.

In [15]:
# Distribución y prevalencia de alérgenos en el dataset (porcentaje sobre el total)
columnas_alergenos = [
        'contains_gluten', 'contains_dairy', 'contains_eggs', 
        'contains_nuts', 'contains_soy', 'contains_fish'
    ]
round(df_food[columnas_alergenos].mean() * 100, 2)

contains_gluten    32.00
contains_dairy     29.86
contains_eggs       6.36
contains_nuts      11.81
contains_soy       16.95
contains_fish       2.24
dtype: float64

Para medir la presencia de cada alérgeno en el dataset, calculamos el promedio de las seis columnas booleanas con .mean() * 100. Como en Python los valores True valen 1 y los False valen 0, Pandas divide la cantidad de positivos por el total de filas, dándonos directamente el porcentaje de productos que contiene cada alérgeno. Los resultados muestran una presencia claramente liderada por ingredientes típicos de alimentos envasados: el gluten (32,00%) y los lácteos (29,86%) aparecen en casi un tercio de la muestra, seguidos por la soja (16,95%) y los frutos secos (11,81%), mientras que el huevo (6,36%) y el pescado (2,24%) tienen una frecuencia mucho más baja y residual dentro de los productos analizados.

Sección 2: Limpieza, Transformación y Curación de los Datos

Objetivo de la sección

Transformar el dataset crudo en una base limpia, coherente y confiable para los análisis posteriores. La idea es eliminar registros repetidos y columnas que no aportan información, corregir el formato de los textos nutricionales para pasarlos a números reales sin perder datos válidos, unificar cómo representamos los datos faltantes corrigiendo el sesgo de las columnas de alérgenos y aplicar reglas de la física y la química de los alimentos para sanear valores imposibles. Por último, compararemos el estado inicial contra el final para verificar el impacto de la limpieza y asegurar que preservamos la mayor cantidad de información útil sin borrar productos innecesariamente.

Tareas que vamos a realizar en esta sección:

Generar una copia del dataset original para poder manipularlo y modifcarlo de manera segura, para despues poder realizar una comparacion de los datos originales y de los datos transformados (2.1)

Cuidar la estructura de la tabla: Eliminar las filas duplicadas exactas para que ningún producto esté repetido y descartar columnas constantes que tengan siempre el mismo valor en todas las filas (2.2).

Convertir los nutrientes a números: Arreglar textos con comas decimales, notación científica o puntos de más para pasarlos a formato decimal (float64) sin generar datos vacíos por error (2.3).

Estandarizar nulos y corregir alérgenos: Reemplazar textos de omisión como 'UNKNOWN' por nulos verdaderos (NaN), y ajustar las columnas de alérgenos para que la falta de declaración figure como dato desconocido y no como un producto seguro (2.4).

Aplicar límites físicos y biológicos de los alimentos: Revisar que no haya valores negativos, topear los nutrientes que superen los 100 gramos por porción, filtrar calorías mayores a 900 kcal, corregir el sodio anotado erróneamente en miligramos y controlar la suma de macronutrientes (2.5).

Auditar y comparar el resultado final: Medir el impacto de la limpieza comparando la tabla antes y después mediante resúmenes estadísticos, justificando el criterio de conservar registros en lugar de eliminar filas completas (2.6).

Seccion 2.1 : Creacion de la copia del dataset.

creamos la copia del dataset para poder modificarla y poderla comparar con los datos del dataset original.

In [16]:
df_food_cp = df_food.copy()
df_food_cp

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.0,0.0,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,65,26,False,False,False,False,False,False,Branded/Packaged
3,Eau minérale naturelle,sidi ali,"en:beverages-and-beverages-preparations, en:be...",100% mineral water,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,65,26,False,False,False,False,False,False,Branded/Packaged
4,اكوافينا,AQUAFINA,"en:beverages-and-beverages-preparations, en:be...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,508,203,False,False,False,False,False,False,Branded/Packaged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,Crème fraîche gastronomique,Président,"en:dairies, en:fermented-foods, en:fermented-m...","_Crème_ (origine France), _ferments lactiques_",D,3.0,A,en:milk,291.0,30.0,...,2.3,0.07,28,False,True,False,False,False,False,Branded/Packaged
4993,Noix de cajou grillées sans sel,Maître Prunille,"en:plant-based-foods-and-beverages, en:plant-b...",Noix de cajou,B,1.0,E,en:nuts,621.0,47.0,...,21.0,0.02,8,False,False,True,False,False,False,Branded/Packaged
4994,Cacao puro en polvo desgrasado,Valor,"en:cocoa-and-its-products, en:cocoa-and-chocol...","Cacao desgrasado en polvo, correctores de acid...",C,1.0,F,NaN,375.0,16.0,...,26.0,0.03,12,False,False,False,False,False,False,Branded/Packaged
4995,Sablés Myrtilles Germes de riz,Gerblé,"en:snacks, en:sweet-snacks, en:biscuits-and-cakes","Farine de blé 58,2%, huile de colza, sucre de ...",A,4.0,C,"en:gluten, en:milk",54.0,2.0,...,0.9,0.05,0.02,True,True,False,False,False,False,Branded/Packaged
4996,Céréales Extra Pepites Kellogg's Chocolat au lait,Kellogg's,"en:plant-based-foods-and-beverages, en:plant-b...","Flocons d'AVOINE(47%), Sucre, Huile de palme, ...",E,4.0,E,"en:gluten, en:milk, en:soybeans",484.0,22.0,...,7.0,0.68,272,True,True,False,True,False,False,Branded/Packaged

Seccion 2.2 : Eliminacion de duplicados y columnas sin variabilidad.

  El objetivo es asegurar que cada fila represente un producto único y que cada columna aporte variabilidad.

In [17]:
df_food_cp = df_food_cp.drop_duplicates()
df_food_cp

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.0,0.0,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,65,26,False,False,False,False,False,False,Branded/Packaged
3,Eau minérale naturelle,sidi ali,"en:beverages-and-beverages-preparations, en:be...",100% mineral water,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,65,26,False,False,False,False,False,False,Branded/Packaged
4,اكوافينا,AQUAFINA,"en:beverages-and-beverages-preparations, en:be...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,508,203,False,False,False,False,False,False,Branded/Packaged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,Crème fraîche gastronomique,Président,"en:dairies, en:fermented-foods, en:fermented-m...","_Crème_ (origine France), _ferments lactiques_",D,3.0,A,en:milk,291.0,30.0,...,2.3,0.07,28,False,True,False,False,False,False,Branded/Packaged
4993,Noix de cajou grillées sans sel,Maître Prunille,"en:plant-based-foods-and-beverages, en:plant-b...",Noix de cajou,B,1.0,E,en:nuts,621.0,47.0,...,21.0,0.02,8,False,False,True,False,False,False,Branded/Packaged
4994,Cacao puro en polvo desgrasado,Valor,"en:cocoa-and-its-products, en:cocoa-and-chocol...","Cacao desgrasado en polvo, correctores de acid...",C,1.0,F,NaN,375.0,16.0,...,26.0,0.03,12,False,False,False,False,False,False,Branded/Packaged
4995,Sablés Myrtilles Germes de riz,Gerblé,"en:snacks, en:sweet-snacks, en:biscuits-and-cakes","Farine de blé 58,2%, huile de colza, sucre de ...",A,4.0,C,"en:gluten, en:milk",54.0,2.0,...,0.9,0.05,0.02,True,True,False,False,False,False,Branded/Packaged
4996,Céréales Extra Pepites Kellogg's Chocolat au lait,Kellogg's,"en:plant-based-foods-and-beverages, en:plant-b...","Flocons d'AVOINE(47%), Sucre, Huile de palme, ...",E,4.0,E,"en:gluten, en:milk, en:soybeans",484.0,22.0,...,7.0,0.68,272,True,True,False,True,False,False,Branded/Packaged

In [18]:
duplicados_restantes = df_food_cp.duplicated().sum()
print(f"Cantidad de filas duplicadas restantes: {duplicados_restantes}")
print(f"Cantidad total de filas tras la eliminacion de los duplicados: {len(df_food_cp)}")

Cantidad de filas duplicadas restantes: 0
Cantidad total de filas tras la eliminacion de los duplicados: 4959

En este paso eliminamos las 38 filas duplicadas exactas que detectamos en el primer diagnóstico, pasando de 4.997 a 4.959 observaciones únicas en la tabla. La presencia de estas filas tiene sentido por el origen de los datos, al venir de Open Food Facts (donde la información la cargan usuarios y aplicaciones comunitarias escaneando códigos de barras con el celular), es normal que un mismo producto envasado se haya registrado o exportado más de una vez con exactamente los mismos valores en cada columna. Además, es clave mirar la proporción, estas 38 filas representan apenas un 0,76% del dataset, por lo que sacarlas no compromete en nada el tamaño de la muestra ni la variedad de alimentos. Si hubiésemos encontrado 3.000 filas repetidas sobre 4.997 (tres quintas partes del total), borrarlas sin un analisis previo hubiera sido una decisión desmedida e incorrecta, ya que delataría que la base se armó mal desde el origen o que hubo un error grave en la exportación. En nuestro caso, al ser una cantidad tan chica, coincide exactamente con el margen de error normal.

In [19]:
df_food_cp = df_food_cp.drop(columns=["food_type"])
df_food_cp

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,fiber_100g,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,False,False,False,False,False,False
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,NaN,8.0,NaN,NaN,False,True,False,False,False,False
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,NaN,65,26,False,False,False,False,False,False
3,Eau minérale naturelle,sidi ali,"en:beverages-and-beverages-preparations, en:be...",100% mineral water,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,NaN,65,26,False,False,False,False,False,False
4,اكوافينا,AQUAFINA,"en:beverages-and-beverages-preparations, en:be...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.0,508,203,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,Crème fraîche gastronomique,Président,"en:dairies, en:fermented-foods, en:fermented-m...","_Crème_ (origine France), _ferments lactiques_",D,3.0,A,en:milk,291.0,30.0,...,NaN,2.3,0.07,28,False,True,False,False,False,False
4993,Noix de cajou grillées sans sel,Maître Prunille,"en:plant-based-foods-and-beverages, en:plant-b...",Noix de cajou,B,1.0,E,en:nuts,621.0,47.0,...,4.5,21.0,0.02,8,False,False,True,False,False,False
4994,Cacao puro en polvo desgrasado,Valor,"en:cocoa-and-its-products, en:cocoa-and-chocol...","Cacao desgrasado en polvo, correctores de acid...",C,1.0,F,NaN,375.0,16.0,...,32.0,26.0,0.03,12,False,False,False,False,False,False
4995,Sablés Myrtilles Germes de riz,Gerblé,"en:snacks, en:sweet-snacks, en:biscuits-and-cakes","Farine de blé 58,2%, huile de colza, sucre de ...",A,4.0,C,"en:gluten, en:milk",54.0,2.0,...,0.5,0.9,0.05,0.02,True,True,False,False,False,False
4996,Céréales Extra Pepites Kellogg's Chocolat au lait,Kellogg's,"en:plant-based-foods-and-beverages, en:plant-b...","Flocons d'AVOINE(47%), Sucre, Huile de palme, ...",E,4.0,E,"en:gluten, en:milk, en:soybeans",484.0,22.0,...,4.9,7.0,0.68,272,True,True,False,True,False,False

Eliminamos la columna entera `food_type` porque, a lo largo de todas las filas del dataset (tanto en las 4.997 iniciales como en las 4.959 que nos quedaron tras sacar los duplicados), tiene exactamente el mismo valor en cada una de ellas, 'Branded/Packaged'.

Desde el punto de vista del análisis de datos, una variable solo sirve si tiene variabilidad, su propósito es permitirnos comparar, armar grupos, encontrar patrones o diferenciar un alimento de otro. Si una columna tiene el mismo texto para el 100% de los registros, no aporta ninguna información útil (en términos estadísticos tiene varianza cero y entropía nula). No nos dice nada nuevo sobre los productos, no ayuda a predecir nada y no sirve para segmentar.

Dejarla en la tabla solo agregaría ruido visual y ocuparía memoria sin ningún beneficio. Al eliminarla por completo, pasamos de 24 a 23 columnas simplificando la estructura del DataFrame, sin perder datos valiosos para las fases que siguen.

Seccion 2.3 Corrección y conversión de tipos de datos 

El objetivo es transformar las 9 variables nutricionales continuas de texto (object/str) a formato flotante (float64), recuperando los datos válidos quefueron mal exportados.

In [20]:
columnas_numericas = ['energy_kcal', 'fat_100g', 'saturated_fat_100g', 'carbs_100g', 'sugars_100g', 'fiber_100g', 'proteins_100g', 'salt_100g', 'sodium_100g']

for col in columnas_numericas :
    col_limpia = df_food_cp[col].astype(str).str.replace("," , ".", regex = False)
    col_limpia = col_limpia.apply(lambda x: str(x).split('.')[0] + '.' + ''.join(str(x).split('.')[1:]) if str(x).count('.') > 1 else x)
    df_food_cp[col]= pd.to_numeric(col_limpia, errors='coerce')
print(df_food_cp.dtypes)

product_name              str
brands                    str
categories                str
ingredients               str
nutriscore_grade          str
nova_group            float64
ecoscore_grade            str
allergens                 str
energy_kcal           float64
fat_100g              float64
saturated_fat_100g    float64
carbs_100g            float64
sugars_100g           float64
fiber_100g            float64
proteins_100g         float64
salt_100g             float64
sodium_100g           float64
contains_gluten          bool
contains_dairy           bool
contains_nuts            bool
contains_soy             bool
contains_eggs            bool
contains_fish            bool
dtype: object

Buscamos estandarizar los valores numéricos bajo el formato estándar de Python (con un único punto decimal y sin separadores de miles) porque es la estructura requerida para trabajar con el tipo float64 y realizar análisis estadísticos, considerando además que al tratarse de nutrientes medidos cada 100 gramos es físicamente imposible tener miles de gramos y los puntos repetidos producto de una exportación defectuosa. Para resolverlo,hicimos lo siguiente, primero conviertimos cualquier coma en punto para uniformar tanto los decimales como la notación científica nativa (como 3,00E-06), luego mediante una partición simple con split('.') conservamos intacto el primer punto decimal y pegamos el resto de las cifras para barrer los puntos sobrantes, y finalmente utilizamos pd.to_numeric() con errors='coerce' para transformar todos los valores de estas columnas a float64 de manera nativa, asegurando que los valores faltantes o nulos se conserven como NaN legítimos sin frenar la ejecución del script.

In [21]:
df_col_num = df_food_cp[columnas_numericas]
df_col_num

,energy_kcal,fat_100g,saturated_fat_100g,carbs_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g
0,0.0,0.0,0.0,4.2,1.4,0.0,0.0,0.00,0.00
1,97.0,3.0,NaN,9.4,NaN,NaN,8.0,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00,26.00
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00,26.00
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,508.00,203.00
...,...,...,...,...,...,...,...,...,...
4992,291.0,30.0,22.0,2.9,2.9,NaN,2.3,0.07,28.00
4993,621.0,47.0,8.7,25.0,6.2,4.5,21.0,0.02,8.00
4994,375.0,16.0,10.0,16.0,0.7,32.0,26.0,0.03,12.00
4995,54.0,2.0,0.2,7.9,1.9,0.5,0.9,0.05,0.02
4996,484.0,22.0,10.0,62.0,25.0,4.9,7.0,0.68,272.00

Logramos corregir con éxito los errores de exportación en las 9 columnas nutricionales, dejando todos los valores bajo el estándar de Pandas (float64) tras sanear comas, puntos de miles repetidos y notaciones científicas. Al conservar únicamente el primer punto decimal y mantener los datos faltantes como NaN legítimos, evitamos distorsionar las proporciones reales de los alimentos y garantizamos que no se pierda información válida. Con esta limpieza lista, la copia de trabajo queda totalmente preparada para encarar la siguiente etapa de análisis exploratorio, cálculo de métricas estadísticas y gráficos sin riesgo de que salte ningún error de tipos.

Seccion 2.4 : Estandarización de nulos y corrección de la trampa de alérgenos.

El objetivo es unificar la representación de la falta de información tanto en texto como en variables booleanas.

In [22]:
# 1. Identificamos las columnas cualitativas (texto)
cols_cualitativas = df_food_cp.select_dtypes(include=["object", "str"]).columns.tolist()

# 2. Lista de nulos camuflados (agregamos el string vacío "")
nulos_camuflados = ["not-applicable", "unknown", "none", "n/a", "null", "nan", "void", "empty", "-", "?", ""]

# 3. Barremos espacios, pasamos a minúsculas y reemplazamos
for col in cols_cualitativas:
    df_food_cp[col] = df_food_cp[col].astype(str).str.strip()
    es_nulo = df_food_cp[col].str.lower().isin(nulos_camuflados)
    df_food_cp.loc[es_nulo, col] = np.nan 

# 4. Verificación
print("Cantidad de valores nulos por columna cualitativa:")
print(df_food_cp[cols_cualitativas].isna().sum())

Cantidad de valores nulos por columna cualitativa:
product_name         176
brands               211
categories            54
ingredients          164
nutriscore_grade     516
ecoscore_grade      1015
allergens           1629
dtype: int64

Estandarizamos los nulos camuflados pasándolos a np.nan porque si dejamos palabras como 'UNKNOWN', 'none', guiones o celdas con puros espacios, Pandas se confunde y los toma como categorías de texto legítimas, falseando por completo los conteos, filtros y métodos como .isna(). Para resolverlo de forma limpia, filtramos automáticamente las columnas cualitativas y armamos una lista con los falsos nulos en minúsculas: primero le mandamos .str.strip() para sacar espacios residuales, después evaluamos la condición con .str.lower().isin() para que atrape cualquier variante sin importar si vino en mayúsculas, minúsculas o título, y finalmente usamos .loc para asignar np.nan únicamente a esas coincidencias, asegurando que el sistema reconozca la verdadera falta de dato.

In [23]:
cols_alergenos = [
    "contains_gluten",
    "contains_dairy",
    "contains_nuts",
    "contains_soy",
    "contains_eggs",
    "contains_fish"
]
df_food_cp[cols_alergenos] = df_food_cp[cols_alergenos].astype('boolean')
allergens_nulos = df_food_cp["allergens"].isna()
df_food_cp.loc[allergens_nulos,cols_alergenos] = np.nan
print (f"\nConteo de nulos: ")
print(df_food_cp[cols_alergenos].isna().sum())

Conteo de nulos:
contains_gluten    1629
contains_dairy     1629
contains_nuts      1629
contains_soy       1629
contains_eggs      1629
contains_fish      1629
dtype: int64

Arreglamos las seis columnas de alérgenos (contains_gluten, contains_dairy, etc.) porque tenian un error grave, si en la columna allergens no se había cargado un valor válido, el dataset le asignaba False a todas por defecto. Lo que hay que tener en cuenta es que no saber si un alimento tiene gluten o leche, no significa que no los tenga, asumir que no tiene nada nos distorciona la realidad y genera un sesgo. Para solucionarlo. Primero obtuvimos las observaciones que tenian el campo ` allergens` en nulo con df_food_cp['allergens'].isna() y luego usando.loc modificamos el valor en las columnas de alérgenos cambiando el False que no tenía sentido por un <NA>,los True y False de los productos que sí tenían los ingredientes declarados quedaron sin modificaciones.

Seccion 2.5 : Tratamiento de inconsistencias y límites de dominio

  El objetivo es aplicar restricciones de dominio químico, nutricional y estequiométrico sobre una base estandarizada de 100 gramos de producto.

In [24]:
# 1. Definimos la lista de variables nutricionales (continuas / de contenido)
cols_nutricionales = [
    'energy_kcal',
    'fat_100g',
    'saturated_fat_100g',
    'carbs_100g',
    'sugars_100g',
    'fiber_100g',
    'proteins_100g',
    'salt_100g',
    'sodium_100g'
]

# 2. Conteo de valores negativos (< 0) por columna
valores_negativos = (df_food_cp[cols_nutricionales] < 0).sum()

print("Cantidad de valores negativos (< 0) por variable nutricional")
print(valores_negativos)

Cantidad de valores negativos (< 0) por variable nutricional
energy_kcal           0
fat_100g              0
saturated_fat_100g    0
carbs_100g            0
sugars_100g           0
fiber_100g            0
proteins_100g         0
salt_100g             0
sodium_100g           0
dtype: int64

Si bien en la primera sección ya habíamos visto que los mínimos no bajaban de cero cuando calculamos el .agg(["min", "max"]), valía la pena volver a hacer una verificación sobre df_food_cp ahora que el dataset ya está duplicado y saneado. Físicamente es imposible que un alimento tenga gramos o calorías negativas, un error que suele aparecer por errores de tipeo en la carga manual o cuando los sistemas asignan valores discernibles como -1. Al evaluar la condición < 0, el conteo dio cero en todas las columnas evaluadas (energy_kcal, grasas, carbohidratos, proteínas, etc.), confirmando de forma estricta que la restricción se cumple en todo el dataset y que no hace falta convertir ningún registro a NaN.

In [25]:
sodio_mayor = ( df_food_cp["sodium_100g"].notna() &
               df_food_cp["salt_100g"].notna() &
               (df_food_cp["sodium_100g"] > df_food_cp["salt_100g"])
            )
inconsistencias_sodio_mayor_sal = sodio_mayor.sum()
print(f"La cantidad de observaciones que contienen mas sodio que sal son { inconsistencias_sodio_mayor_sal}")

cols_sal_sodio = ["product_name", "salt_100g", "sodium_100g"]
df_food_cp.loc[sodio_mayor,cols_sal_sodio].head()

La cantidad de observaciones que contienen mas sodio que sal son 1956

                     product_name  salt_100g  sodium_100g
9                            Jben       0.46        184.0
20  Edelbitterschokolade Mild 90%       0.03         12.0
23                        Nutella     107.00        428.0
24                    Cappy PULPY     126.00        504.0
28                         Sésame       0.38        152.0

In [26]:
df_food_cp.loc[sodio_mayor, "sodium_100g"] = df_food_cp.loc[sodio_mayor, "sodium_100g"] / 1000

sodio_mayor_post_revision = ( df_food_cp["sodium_100g"].notna() &
                            df_food_cp["salt_100g"].notna() &
                            (df_food_cp["sodium_100g"] > df_food_cp["salt_100g"])
                        )
inconsistencias_sodio_mayor_sal_post_coreccion = sodio_mayor_post_revision.sum()
print (f"La cantidad de observaciones con mas sodio que sal luego de la correccion de las unidades del sodio es de {inconsistencias_sodio_mayor_sal_post_coreccion}")

La cantidad de observaciones con mas sodio que sal luego de la correccion de las unidades del sodio es de 1

In [27]:
# Sinceramos el único caso residual imposible como NaN
df_food_cp.loc[sodio_mayor_post_revision, "sodium_100g"] = np.nan

Comparamos la sal contra el sodio teniendo en cuenta la regla química de que la sal siempre debe ser mayor al sodio (la sal de mesa es cloruro de sodio y el sodio representa solo un 40% de su peso: Sal = Sodio * 2,54). Encontramos 1.956 productos donde el sodio superaba a la sal. Al mirar los valores, confirmamos que se trataba de un error sistemático de unidades, los datos de sodio estaban cargados en miligramos en lugar de gramos (por ejemplo, 184 mg en vez de 0,184 g). Como la información no estaba corrupta sino mal escalada, corregimos esas 1.956 celdas dividiendo el sodio por 1.000 mediante indexación con .loc. Con esto recuperamos la escala correcta en gramos y la coherencia en toda la columna sin perder un solo registro. Como quedo un registro en donde la cantidad de sodio superaba la cantidad de sal probablemente por un error manual de carga. En este caso asignamos el valor np.nan.

In [28]:
cols_regla_100g = [ "fat_100g" ,"saturated_fat_100g", "carbs_100g", "proteins_100g" , "sugars_100g", "fiber_100g", "salt_100g", "sodium_100g"]

conteo_supera_100 = (df_food_cp[cols_regla_100g] > 100).sum()

conteo_supera_100

fat_100g               42
saturated_fat_100g    126
carbs_100g             12
proteins_100g          20
sugars_100g            39
fiber_100g             27
salt_100g             525
sodium_100g           243
dtype: int64

In [29]:
for col in cols_regla_100g:
    df_food_cp.loc[df_food_cp[col] > 100, col] = np.nan
print("Control despues de hacer la limpieza:")
print(f"La cantidad de macros que superan los 100g es de {(df_food_cp[cols_regla_100g] > 100).sum()}")

Control despues de hacer la limpieza:
La cantidad de macros que superan los 100g es de fat_100g              0
saturated_fat_100g    0
carbs_100g            0
proteins_100g         0
sugars_100g           0
fiber_100g            0
salt_100g             0
sodium_100g           0
dtype: int64

Al aplicar la restricción física de que ningún componente individual puede superar los 100 g por porción, encontramos varias inconsistencias de dominio bastante marcadas: 525 registros en sal (salt_100g), 42 en grasas, 39 en azúcares, 27 en fibra, 20 en proteínas, 243 en sodio, 126 en grasas saturadas y 12 en carbohidratos. El caso grosero de la sal se explica principalmente por el clásico error de carga donde se ingresaron miligramos en lugar de gramos (por ejemplo, cargar 500 g de sal en vez de 500 mg), mientras que el resto responde a errores de tipeo o escalas erróneas. Para limpiar estas observaciones sin perder los productos enteros (que quizás tenían bien cargadas las calorías u otros campos), filtramos con .loc sobre cada columna y convertimos esos valores a np.nan. Tras la corrección, verificamos que el 100% de los datos numéricos individuales respeta el límite físico de 100 g.

In [30]:
# 1. Sumamos los macronutrientes
suma_macros = df_food_cp['fat_100g'] + df_food_cp['carbs_100g'] + df_food_cp['proteins_100g']

# 2. Conteo de infractores
print("Productos con suma de macros > 100g:", (suma_macros > 100).sum())

# 3. Nombres exactos de las columnas corregidos
columnas_interes = ["product_name", "proteins_100g", "carbs_100g", "fat_100g"]

# 4. Filtramos usando la variable suma_macros (sin comillas)
df_food_cp[suma_macros > 100][columnas_interes]

Productos con suma de macros > 100g: 20

,product_name,proteins_100g,carbs_100g,fat_100g
232,Rye and mixed seed sourdough bread,8.600000,88.000000,8.600000
425,Classic Torinesi Breadsticks,19.800000,75.000000,6.500000
477,White Sourdough Toastie Loaf,25.000000,65.000000,13.000000
856,Lio produit,1.000000,0.000000,100.000000
1040,sucre arôme vanille,1.430000,100.000000,0.000000
1440,top cookies original,5.800000,70.000000,25.400000
1445,Tartines craquantes Froment,11.700000,73.900000,23.400000
1646,Classic Yellow Mustard,43.000000,47.000000,44.000000
1881,cassonade,0.500000,100.000000,0.500000
2000,Oreo chocolate,7.840000,78.400000,19.600000
2286,Ketchup stat 330g,1.128000,25.700000,88.000000
2552,Chips chili,53.000002,45.000000,37.000000
2553,Fruity favourites,50.588235,10.823529,51.764706
2687,Pizzarella premium,8.000000,63.000000,40.000000
2986,Shortbread fingers,55.999999,60.000000,27.000000
3278,Heinz Mayonesa,0.800000,30.000000,70.000000
3341,Frusli Juicy Blueberries Chewy Cereal Bars 6 x...,56.999998,72.900002,69.000001
3710,Multigrain Cheerios,93.333333,71.000000,5.000000
3870,Crème chantilly,4.000000,68.000000,32.000000
4501,Real Mayonnaise,1.000000,34.000001,74.000000

In [31]:

#Filtramos los índices de los casos con inconsistencias (> 105g)
indices_inconsistentes = df_food_cp[suma_macros > 105].index
print(f"Cantidad de filas a descartar: {len(indices_inconsistentes)}")

# 3. Borramos esas observaciones del DataFrame
df_food_cp = df_food_cp.drop(index=indices_inconsistentes)

#Verificación rápida
suma_macros_post = df_food_cp['fat_100g'] + df_food_cp['carbs_100g'] + df_food_cp['proteins_100g']
print(f"Casos restantes > 105g: {(suma_macros_post > 105).sum()}")
print(f"Casos tolerados por redondeo (100g a 105g): {((suma_macros_post > 100) & (suma_macros_post <= 105)).sum()}")

Cantidad de filas a descartar: 12
Casos restantes > 105g: 0
Casos tolerados por redondeo (100g a 105g): 8

Para chequear el balance de masa (la suma de grasas, carbohidratos y proteínas no puede superar los 100 g de materia), nos encontramos con 20 productos que rompían la regla física, pero con dos situaciones muy distintas. Por un lado, 8 registros tenían un exceso mínimo (entre 100 g y 105 g), lo cual es esperable por el redondeo comercial que exige la normativa de etiquetado al pasar decimales a enteros en el paquete; esos datos los dejamos intactos porque los consideramos válidos. Por el otro lado, encontramos 12 registros con desfasajes groseros (sumas de 135 g hasta casi 200 g), producto de errores evidentes de tipeo o escalas mal aplicadas. Descartamos inventar datos reescalándolos con una regla de tres (ya que asumiríamos una proporción arbitraria sin conocer la receta), y en lugar de llenar de nulos media fila, directamente eliminamos esos 12 productos con .drop(). Representan apenas un 0,24% del dataset y un alimento con una tabla nutricional tan corrupta no aporta nada confiable al análisis posterior.

In [32]:
calorias_invalidas = df_food_cp["energy_kcal"] > 900
total_filas_con_calorias_invalidas = calorias_invalidas.sum()
print (f"La cantidad de filas que contiene mas de 900kcal por cada 100g de producto es de {total_filas_con_calorias_invalidas}")
cols_macros = ['product_name', 'energy_kcal', 'fat_100g', 'carbs_100g', 'proteins_100g']
df_food_cp.loc[calorias_invalidas, cols_macros]

La cantidad de filas que contiene mas de 900kcal por cada 100g de producto es de 2

     product_name  energy_kcal  fat_100g  carbs_100g  proteins_100g
346       Biscoff        937.0      19.2        73.1           5.13
2446      Havarti       1580.0       NaN         5.2          76.00

In [33]:
# 1. Anulamos únicamente las calorías imposibles (> 900 kcal)
df_food_cp.loc[calorias_invalidas, 'energy_kcal'] = np.nan

# 2. Verificación de control post-saneamiento
print("Casos restantes con energy_kcal > 900:", (df_food_cp['energy_kcal'] > 900).sum())

Casos restantes con energy_kcal > 900: 0

Aplicamos la restricción de densidad energética máxima teórica (900 kcal por cada 100 g, equivalente al límite fisico el cual es la grasa pura), ya que ningún alimento real puede superar este umbral. El chequeo identificó únicamente dos registros que no cumplen esta restricción: unas galletitas Biscoff (937 kcal), cuyo aporte real por sus macronutrientes deberia ser 485 kcal lo que nos muestra un error de carga manual, y un queso Havarti (1.580 kcal), en este caso es una confusión de unidades donde se ingresó el valor en kilojulios (1.580 kJ equivalen a ≈ 377 kcal) directamente en el campo de kilocalorías. Como los restantes atributos de ambos productos son válidos, se procedió a sanear exclusivamente el campo energy_kcal asignándole np.nan mediante .loc, preservando el resto de la observación y asegurando la coherencia del dataset.

In [34]:
grasa_inconsistente = (
        df_food_cp["saturated_fat_100g"].notna() &
        df_food_cp["fat_100g"].notna() &
        (df_food_cp["saturated_fat_100g"] > df_food_cp["fat_100g"])
    )
print(f"Productos con grasas saturadas mayores a grasas totales: {grasa_inconsistente.sum()}")

Productos con grasas saturadas mayores a grasas totales: 18

In [35]:
df_food_cp.loc[grasa_inconsistente, "saturated_fat_100g"] = np.nan
grasa_inconsistente_post_correccion = (
        df_food_cp["saturated_fat_100g"].notna() &
        df_food_cp["fat_100g"].notna() &
        (df_food_cp["saturated_fat_100g"] > df_food_cp["fat_100g"])
    )
print(f"Productos con grasas saturadas mayores a grasas totales: {grasa_inconsistente_post_correccion.sum()}")

Productos con grasas saturadas mayores a grasas totales: 0

In [36]:
# 1. Identificamos casos donde los azúcares superan a los carbohidratos totales
azucar_inconsistente = (
        df_food_cp["sugars_100g"].notna() &
        df_food_cp["carbs_100g"].notna() &
        (df_food_cp["sugars_100g"] > df_food_cp["carbs_100g"])
    )
print(f"Productos con azúcares mayores a carbohidratos: {azucar_inconsistente.sum()}")

Productos con azúcares mayores a carbohidratos: 16

In [37]:
df_food_cp.loc[azucar_inconsistente, "sugars_100g"] = np.nan
azucar_inconsistente_post_correccion = (
        df_food_cp["sugars_100g"].notna() &
        df_food_cp["carbs_100g"].notna() &
        (df_food_cp["sugars_100g"] > df_food_cp["carbs_100g"])
    )
print(f"Productos con azúcares mayores a carbohidratos: {azucar_inconsistente_post_correccion.sum()}")

Productos con azúcares mayores a carbohidratos: 0

Por definición nutricional y química, las grasas saturadas son una fracción de las grasas totales, al igual que los azúcares simples forman parte de los hidratos de carbono totales. Tras revisar estas incosistencias, se detectaron 18 registros donde las grasas saturadas superaban a las totales y 16 donde los azúcares superaban a los carbohidratos. Al no poder determinar cuál de los dos valores fue cargado de manera erronea por el usuario, se procedió a anular la fracción secundaria mediante np.nan para preservar la coherencia del conjunto sin descartar el producto.

Sección 2.6: Limpieza de variables cualitativas y extracción de atributos.

En esta subsección nos encargamos de limpiar y estructurar las variables categóricas y de texto libre. El objetivo es concreto: corregir el tipo de dato de nova_group a enteros, limpiar marcas y nombres de producto para eliminar duplicados por diferencias de tipeo, normalizar la escala de ecoscore y generar dos variables nuevas a partir del texto. De esta forma transformamos campos desordenados en variables homogéneas y directamente analizables para el EDA.

In [48]:
df_food_cp["nova_group"] = df_food_cp["nova_group"].astype("Int64")
print(f"El tipo de la variable nova_group ahora es {df_food_cp['nova_group'].dtype}")
print(df_food_cp["nova_group"].value_counts(dropna=False).sort_index())

El tipo de la variable nova_group ahora es Int64
nova_group
1        580
2        208
3       1089
4       2627
<NA>     443
Name: count, dtype: Int64

Convertimos la columna nova_group de float64 a un tipo entero nullable (Int64). La clasificación NOVA es una escala cualitativa ordinal y estrictamente discreta (los grupos van del 1 al 4 y no admiten decimales intermedios como 1.5 o 2.0). Utilizar Int64 nos permite representar la naturaleza entera de la variable respetando los valores faltantes originales como NA, sin forzar la columna a números de punto flotante.

In [39]:
productos_antes = df_food_cp["product_name"].nunique()
marcas_antes = df_food_cp["brands"].nunique()

df_food_cp["product_name"] = df_food_cp["product_name"].str.strip().str.lower()
df_food_cp["brands"] = df_food_cp["brands"].str.strip().str.lower()

productos_despues = df_food_cp["product_name"].nunique()
marcas_despues = df_food_cp["brands"].nunique()

print(f"Marcas únicas: pasaron de {marcas_antes} a {marcas_despues} (reducción de {marcas_antes - marcas_despues})")
print(f"Nombres únicos: pasaron de {productos_antes} a {productos_despues} (reducción de {productos_antes - productos_despues})")

Marcas únicas: pasaron de 2059 a 1792 (reducción de 267)
Nombres únicos: pasaron de 4406 a 4231 (reducción de 175)

Estandarizamos los campos de texto brands y product_name pasando todos los caracteres a minúsculas y removiendo espacios en blanco al inicio y al final mediante funciones de Pandas. Esta transformación unifica registros que diferían únicamente por cuestiones de tipeo o uso de mayúsculas (por ejemplo, variantes tipográficas de una misma marca comercial), preservando los valores nulos originales sin convertirlos a texto y reduciendo notablemente la cantidad de categorías redundantes para facilitar futuras agrupaciones.

In [40]:
df_food_cp["main_category"] = df_food_cp["categories"].dropna().str.split(",").str[0].str.lower().str.replace(r"^[a-z]{2}:", "", regex=True).str.strip()
df_food_cp['main_category'].value_counts().head(10)

main_category
plant-based-foods-and-beverages         1876
snacks                                   861
dairies                                  653
beverages-and-beverages-preparations     543
condiments                               306
breakfasts                               118
seafood                                   91
beverages                                 69
meats-and-their-products                  65
meals                                     50
Name: count, dtype: int64

Creamos la columna main_category a partir de categories para quedarnos únicamente con la categoría principal de cada producto y sacarle los prefijos de idioma (como en: o es:). La columna original venía con listas largas de etiquetas mezcladas y textos poco prácticos para agrupar, así que aislar la familia principal del alimento nos permite tener una variable categórica limpia y directa para comparar productos, filtrar y armar gráficos sin complicaciones.

In [41]:
df_food_cp["ingredients"] = df_food_cp["ingredients"].dropna().str.split().str.join(" ").str.strip().str.lower()
df_food_cp["ingredients_count"] = df_food_cp["ingredients"].dropna().str.split(",").str.len().astype("Int64")
df_food_cp[["ingredients","ingredients_count"]]

                                            ingredients  ingredients_count
0                     obd1 999 999 1112606 266963207 mb                  1
1            milk cream, cream, sugar, banana, bacteria                  5
2     sodium, calcium, magnésium, potassium, bicarbo...                  8
3                                    100% mineral water                  1
4     ouverture et avant le : voir bouteille. après ...                  1
...                                                 ...                ...
4992     _crème_ (origine france), _ferments lactiques_                  2
4993                                      noix de cajou                  1
4994  cacao desgrasado en polvo, correctores de acid...                  3
4995  farine de blé 58,2%, huile de colza, sucre de ...                 22
4996  flocons d'avoine(47%), sucre, huile de palme, ...                 23

[4947 rows x 2 columns]

A partir del texto de ingredients (que ya habíamos dejado prolijo sin saltos de línea ni espacios dobles), creamos ingredients_count contando la cantidad de componentes separados por comas y guardándolo como un número entero (Int64). Esto nos permite transformar un campo de texto libre en una métrica cuantitativa muy útil para evaluar el grado de procesamiento del producto (diferenciando alimentos simples de 1 o 2 ingredientes frente a ultraprocesados con fórmulas de más de 20), dejando como nulos (<NA>) a los que no tenían ingredientes cargados en lugar de inventar un cero falso.

In [42]:
df_food_cp['ecoscore_grade'].value_counts(dropna=False)

ecoscore_grade
NaN       1015
B          892
A          817
D          714
C          637
E          508
A-PLUS     257
F          107
Name: count, dtype: int64

In [43]:
# Definimos los valores fuera de la escala oficial
escala_invalida = ["A-PLUS", "F"]
fuera_escala = df_food_cp['ecoscore_grade'].isin(escala_invalida)

print(f"Registros con valores inválidos identificados: {fuera_escala.sum()}")

# Asignamos NaN a las observaciones identificadas
df_food_cp.loc[fuera_escala, 'ecoscore_grade'] = np.nan

print("\nDistribución final de ecoscore_grade (incluyendo nulos):")
print(df_food_cp['ecoscore_grade'].value_counts(dropna=False))

Registros con valores inválidos identificados: 364

Distribución final de ecoscore_grade (incluyendo nulos):
ecoscore_grade
NaN    1379
B       892
A       817
D       714
C       637
E       508
Name: count, dtype: int64

Revisamos la columna ecoscore_grade para que respete la escala oficial del Eco-Score, que va únicamente de la A a la E (igual que el Nutri-Score). Al inspeccionar los datos encontramos 257 productos con A-PLUS y 107 con F, valores que no existen en la escala estándar. En vez de borrar las filas enteras o inventar una equivalencia a mano, decidimos transformar esos valores inválidos en nulos (np.nan) usando .loc. Así dejamos la variable limpia y comparable con las demás métricas, sin perder el resto de los datos de cada producto.

In [44]:
df_food_cp["nutriscore_grade"].value_counts()

nutriscore_grade
C    1068
E     990
D     898
A     830
B     646
Name: count, dtype: int64

Revisamos la columna nutriscore_grade haciendo un conteo de sus valores y confirmamos que todas las categorías registradas pertenecen a la escala oficial (A, B, C, D y E). Como no encontramos valores raros, textos mal escritos ni etiquetas fuera de norma, no hace falta aplicarle ninguna limpieza ni transformación; la columna ya está lista para usarse tal como está.

Sección 2.7: Balance final y auditoria post-limpieza.

El objetivo de esta subsección es auditar el estado integral del dataset tras todas las operaciones de curación, verificando dimensiones, consistencia de tipos y cumplimiento estricto de los dominios físicos y estadísticos.

In [45]:
filas_finales = df_food_cp.shape[0]
columnas_finales = df_food_cp.shape[1]
print(f"Dimensiones finales del dataset limpio : {filas_finales} filas , {columnas_finales} columnas")

Dimensiones finales del dataset limpio : 4947 filas , 25 columnas

Las dimensiones finales del dataframe reflejan todo el proceso de limpieza desde el inicio, la cantidad de filas se redujo de 4.997 a 4.947 debido a la eliminación inicial de 38 duplicados exactos y al posterior descarte de 12 observaciones con inconsistencias estequiométricas groseras en la suma de macronutrientes. Ante valores inválidos o faltantes (como en ecoscore_grade) preferimos convertirlos en nulos con .loc en lugar de borrar filas enteras y perder datos útiles de otras columnas; y por el otro lado, la cantidad de columnas aumentó porque sumamos variables derivadas como main_category e ingredients_count para transformar texto libre en categorías limpias y métricas numéricas, logrando una tabla final sin duplicados, con datos estandarizados y con nuevas dimensiones analíticas listas para graficar y explorar.

In [47]:
columnas_cuantitativas = [
        'energy_kcal', 'fat_100g', 'saturated_fat_100g', 'carbs_100g', 
        'sugars_100g', 'fiber_100g', 'proteins_100g', 'salt_100g', 
        'sodium_100g', 'ingredients_count'
    ]
df_food_cp[columnas_cuantitativas].describe()

,energy_kcal,fat_100g,saturated_fat_100g,carbs_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g,ingredients_count
count,4666.000000,4639.000000,4459.000000,4650.000000,4563.000000,3458.000000,4656.000000,4115.000000,4395.000000,4783.0
mean,299.807160,15.973326,5.508483,30.577549,12.190067,4.305863,7.250913,2.581254,1.681711,9.869956
std,208.446345,20.491366,9.054132,27.657597,17.712373,5.172500,7.091905,9.684035,7.665004,8.182761
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,99.000000,1.500000,0.300000,4.800000,1.100000,0.500000,1.700000,0.050000,0.020000,3.0
50%,295.000000,7.600000,1.700000,19.250000,4.300000,3.000000,6.300000,0.510000,0.192000,8.0
75%,456.000000,23.000000,7.100000,57.775000,16.000000,6.600000,9.700000,1.220000,0.460000,14.0
max,900.000000,100.000000,100.000000,100.000000,100.000000,66.000000,90.000000,100.000000,98.000000,68.0

Hicimos esta auditoría sobre las variables cuantitativas mediante .describe() como un control de calidad final para asegurarnos de que los datos tengan coherencia física y estadística antes de ponernos a graficar. Lo que vemos confirma que los datos quedaron consistentes: los nutrientes respetan el rango lógico de 0 a 100 g, la energía alcanza un máximo de 900 kcal (esperable en alimentos a base de grasa pura como los aceites) y nuestra nueva columna ingredients_count se comporta de forma muy natural, yendo de 1 a 68 ingredientes con una mediana de 8. Además, este resumen nos permite anticipar que la mayoría de los nutrientes presentan una asimetría hacia la derecha (con medias superiores a las medianas) y deja en el radar algunos valores extremos en sal y sodio para prestarles atención durante el análisis exploratorio.

El balance de esta etapa de limpieza es súper positivo porque dejamos el dataset prolijo, coherente y con sentido físico para ponernos a analizar. A nivel estructura, arrancamos eliminando 38 registros duplicados, sacamos la columna food_type porque tenía un solo valor y no aportaba nada, y descartamos 12 productos que tenían errores imposibles en la suma de sus macronutrientes (superaban los 100 g), llegando así a las 4.947 observaciones finales. En la parte numérica, convertimos los 9 nutrientes a decimales (float64), filtramos valores absurdos (más de 100 g o más de 900 kcal) y corregimos el sodio que venía desfasado en miligramos para pasarlo a gramos. Por último, en las variables de texto y categorías, desenmascaramos los nulos que venían disfrazados, corregimos el falso negativo en los alérgenos, dejamos nova_group como entero (Int64), estandarizamos ecoscore_grade para que solo use las letras oficiales (A a la E) y sumamos dos variables nuevas clave: la categoría principal limpia (main_category) y el conteo de ingredientes (ingredients_count). Con todo esto resuelto, la tabla quedó consistente, sin pérdida innecesaria de datos y lista para arrancar de lleno con los gráficos y el análisis exploratorio.